<template>
  <main class="flow-page">
    <section class="header">
      <p class="eyebrow">Proposed Method · 3.1</p>
      <h1>Inputs, Parameters, and Tokens</h1>
      <p class="subtitle">
        FabGPT transforms the query image, OCR text marks, labels, masks, and user question into prompt instructions.
      </p>
    </section>

    <section class="main">
      <section class="left">
        <p class="label">Input and Initial Encoding</p>
        <h2>From SEM image to CLIP vectors</h2>

        <div class="formula">
          <span>x ∈ R<sup>H × W × 3</sup></span>
          <span>OCR(x) → text marks</span>
          <span>x, text marks, label set → V<sub>img</sub><sup>clip</sup>, V<sub>txt</sub><sup>clip</sup>, V<sub>lab</sub><sup>clip</sup></span>
        </div>
      </section>

      <section class="right">
        <p class="label">Parameter Map</p>

        <div class="row">
          <span>P<sub>n</sub></span>
          <p>Predicted defect category from the Prediction Module.</p>
        </div>

        <div class="row">
          <span>V<sub>img</sub>, V<sub>txt</sub></span>
          <p>Enhanced image and text vectors generated by multiplying P<sub>n</sub> with CLIP features.</p>
        </div>

        <div class="row">
          <span>T<sub>img</sub>, T<sub>txt</sub></span>
          <p>Information-rich image and text tokens produced by visual and textual adapters.</p>
        </div>

        <div class="row">
          <span>T<sub>mas</sub></span>
          <p>Mask-projected token generated from the detection stage.</p>
        </div>

        <div class="row">
          <span>T<sub>que</sub>, aT<sub>vis</sub></span>
          <p>User question token and unified visual token aligned by the Modulation Module.</p>
        </div>
      </section>
    </section>

    <section class="bottom">
      <strong>Final prompt instruction:</strong>
      <span>aT<sub>vis</sub> + T<sub>mas</sub> + T<sub>que</sub> → fine-tuning PandaGPT</span>
    </section>
  </main>
</template>

<style scoped>
.flow-page {
  width: 100%;
  height: 100%;
  box-sizing: border-box;
  padding: 24px 64px;
  overflow: hidden;
  background:
    radial-gradient(circle at 82% 18%, rgba(95, 127, 137, 0.12), transparent 30%),
    radial-gradient(circle at 20% 88%, rgba(95, 127, 137, 0.08), transparent 34%),
    linear-gradient(135deg, #fbfbf8 0%, #eef3f4 58%, #fbfbf8 100%);
  color: #1f2933;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
}

.eyebrow,
.label {
  color: #5f7f89;
  font-size: 10px;
  font-weight: 500;
  letter-spacing: 0.17em;
  text-transform: uppercase;
}

.eyebrow {
  margin: 0 0 6px;
}

h1 {
  margin: 0;
  color: #314f5a;
  font-family: Georgia, Cambria, "Times New Roman", serif;
  font-size: 36px;
  line-height: 1.04;
  font-weight: 400;
}

.subtitle {
  margin: 7px 0 0;
  color: #8a9ca3;
  font-size: 12.6px;
}

.main {
  margin-top: 40px;
  display: grid;
  grid-template-columns: 0.9fr 1.1fr;
  gap: 60px;
  align-items: start;
}

.label {
  margin: 0 0 13px;
}

.left h2 {
  margin: 0;
  color: #1f2933;
  font-family: Georgia, Cambria, "Times New Roman", serif;
  font-size: 34px;
  line-height: 1.07;
  font-weight: 400;
}

.formula {
  margin-top: 28px;
  display: grid;
  gap: 13px;
}

.formula span {
  padding: 13px 15px;
  border-radius: 18px;
  background: rgba(255, 255, 255, 0.58);
  border-left: 4px solid rgba(95, 127, 137, 0.42);
  color: #314f5a;
  font-size: 13px;
  line-height: 1.35;
  transition: 160ms ease;
}

.row {
  display: grid;
  grid-template-columns: 92px 1fr;
  gap: 16px;
  align-items: start;
  padding: 10px 0 11px;
  border-bottom: 1px solid rgba(120, 145, 154, 0.22);
  transition: 160ms ease;
}

.row span {
  color: #1f2933;
  font-family: Georgia, Cambria, "Times New Roman", serif;
  font-size: 20px;
  line-height: 1;
}

.row p {
  margin: 0;
  color: #6b7d86;
  font-size: 11.8px;
  line-height: 1.28;
}

.formula span:hover,
.row:hover,
.bottom:hover {
  transform: translateX(7px);
}

.bottom {
  margin-top: 26px;
  padding: 14px 18px;
  border-radius: 22px;
  background: rgba(255, 255, 255, 0.56);
  border: 1px solid rgba(120, 145, 154, 0.20);
  color: #314f5a;
  font-size: 13px;
  transition: 160ms ease;
}

.bottom strong {
  color: #1f2933;
  margin-right: 10px;
}
</style>